# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 12:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0040_auto_20160720_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='face_value',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True, verbose_name='Nominal value of this asset'),
        ),
        migrations.AddField(
            model_name='security',
            name='number_segments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='JSON list of segments of ids for securities. can be 1, 2, 3, 4-10'),
        ),
        migrations.AlterField(
            model_name='security',
            name='track_numbers',
            field=models.BooleanField(default=False, verbose_name='Verwaltung nummerierter Aktien ist aktiviert.'),
        ),
    ]
