# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 20:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0041_auto_20160720_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='number_segments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name='JSON list of segments of ids for securities. can be 1, 2, 3, 4-10'),
        ),
    ]
