# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 21:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0042_auto_20160720_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionplan',
            name='number_segments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name="JSON Liste der IDs der Wertpapiere. Kann [1,2,3, u'5-9'] sein."),
        ),
        migrations.AddField(
            model_name='optiontransaction',
            name='number_segments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name="JSON Liste der IDs der Wertpapiere. Kann [1,2,3, u'5-9'] sein."),
        ),
        migrations.AddField(
            model_name='position',
            name='number_segments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name="JSON Liste der IDs der Wertpapiere. Kann [1,2,3, u'5-9'] sein."),
        ),
        migrations.AlterField(
            model_name='security',
            name='face_value',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True, verbose_name='Nominalwert'),
        ),
        migrations.AlterField(
            model_name='security',
            name='number_segments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name="JSON Liste der IDs der Wertpapiere. Kann [1,2,3, u'5-9'] sein."),
        ),
    ]
