# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 21:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0043_auto_20160720_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionplan',
            name='number_segments',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name="JSON Liste der IDs der Wertpapiere. Kann [1,2,3, u'5-9'] sein."),
        ),
        migrations.AlterField(
            model_name='optiontransaction',
            name='number_segments',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name="JSON Liste der IDs der Wertpapiere. Kann [1,2,3, u'5-9'] sein."),
        ),
        migrations.AlterField(
            model_name='position',
            name='number_segments',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name="JSON Liste der IDs der Wertpapiere. Kann [1,2,3, u'5-9'] sein."),
        ),
    ]
